
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: store_hook
      description: "An example model of store"
      columns:
      - name: s_store_id
        tests:
          - unique
          - not_null 
      - name: s_market_id
        tests:
          - relationships:
              to: ref('store_hook')
              field: id